name: First Workflow
on: [push,workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print Jai Hind. Good bye
        run: echo "Jai Hind.. Good bye Done - bye!"
